beam_size: 300
max_source_length: 256
max_target_length: 128
debugeval_bugsinfo_path: /home/debugeval/NPR4J_Result/data/npr4j_additional_bug_loc_statistics.json
load_model_path: /home/debugeval/NPR4J_Result/models/CodeBERT_trained/pytorch_model.bin
pred_file: /home/debugeval/NPR4J_Result/results/codeBert/npr4j_additional_CodeBertFT_pred.txt
debugeval_output_dir: /home/debugeval/NPR4J_Result/results/codeBert
eval_batch_size: 1
do_train: False
do_eval: False
do_test: True
model_type: roberta
model_name_or_path: /home/debugeval/NPR4J_Result/models/codebert-base